#!/bin/bash

workspaces() {

	local icons_dp=("一" "二" "三" "四" "五")
	local icons_hdmi=("六" "七" "八" "九" "十")
	local output="(box :class \"workspaces\" :orientation \"v\" :halign \"center\" :valign \"start\" :space-evenly \"false\" :spacing \"5\" "
	local icons

	if [[ $1 == "dp" ]]; then
		icons=("${icons_dp[@]}")
	elif [[ $1 == "hdmi" ]]; then
		icons=("${icons_hdmi[@]}")
	else
		exit
	fi
	for w in "${icons[@]}"; do
		output="${output} (button :onclick \"bspc desktop -f ${w}\" "
		focused=$(bspc query -D -d focused --names | grep "$w")
		if [[ "$focused" == "$w" ]]; then
			output="${output} :class \"focused\" "
		elif [[ "$(bspc query -D -d .occupied --names | grep "$w")" == "$w" ]]; then
			output="${output} :class \"occupied\" "
		fi
		output="${output} \"$w\")"
	done
	output="${output})"
	echo "$output"
}

workspaces "$1"
bspc subscribe desktop node_transfer | while read -r _; do
	workspaces "$1"
done
